[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = 'test'
optimizer = true
optimizer_runs = 10_000
solc = "0.8.24"
gas_reports = ["*"]
fs_permissions = [{ access = "read", path = "./"}]

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "preserve"
override_spacing = true
ignore = [
    "src/lib/StorageLib.sol"
]

[profile.test]
no_match_test = "(Fuzz|invariant_)"
no_match_contract = "(Fuzz|CryticERC4626TestsHarness)"
gas_reports = ["*"]

[profile.fuzz]
runs = 1000
max_local_rejects = 1024
max_global_rejects = 65536
seed = '0x3e8'
dictionary_weight = 100
include_storage = true
include_push_bytes = true
match_test = "Fuzz"
match_contract = "Fuzz"

[profile.ci_fuzz]
runs = 50000
max_local_rejects = 1024
max_global_rejects = 65536
seed = '0x3e8'
dictionary_weight = 100
include_storage = true
include_push_bytes = true
match_test = "Fuzz"
match_contract = "Fuzz"

[profile.invariant]
runs = 256
depth = 500
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
match_test = "invariant_"

[profile.coverage]
via_ir = true
no_match_test = "(invariant_)"
no_match_contract = "(Script|CryticERC4626TestsHarness)"
no_match_coverage= "(script|test|fuzz|e2e)"

[profile.coverage.optimizer_details]
constantOptimizer = true
yul = true

[profile.coverage.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = ''

[doc]
out = "foundry-docs/"
title = "Euler Yield Aggregator Contracts Documentation"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
