name: Echidna Enigma Invariants

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  echidna_property_mode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Clone the private repo into corpus folder
        run: |
          git clone git@github.com:Enigma-Dark/euler-earn-corpus.git corpus

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Compile contracts
        run: |
          forge build --build-info

      - name: Run Echidna Property Mode
        uses: crytic/echidna-action@v2
        with:
          files: .
          contract: Tester
          config: test/enigma-dark-invariants/_config/echidna_config_ci.yaml
          crytic-args: --ignore-compile

  echidna_assertion_mode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Compile contracts
        run: |
          forge build --build-info

      - name: Run Echidna Assertion Mode
        uses: crytic/echidna-action@v2
        with:
          files: .
          contract: Tester
          config: test/enigma-dark-invariants/_config/echidna_config_ci.yaml
          test-mode: assertion
          crytic-args: --ignore-compile
