name: Echidna Enigma Invariants

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Compile contracts
        run: |
          forge build --build-info

  echidna_property_mode:
    runs-on: ubuntu-latest
    needs: test # Ensure contracts are compiled before this job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Echidna Property Mode
        uses: crytic/echidna-action@v2
        with:
          files: test/enigma-dark-invariants/Tester.t.sol
          contract: Tester
          config: test/enigma-dark-invariants/_config/echidna_config_ci.yaml

  echidna_assertion_mode:
    runs-on: ubuntu-latest
    needs: test # Ensure contracts are compiled before this job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Run Echidna Assertion Mode
        uses: crytic/echidna-action@v2
        with:
          files: test/enigma-dark-invariants/Tester.t.sol
          contract: Tester
          config: test/enigma-dark-invariants/_config/echidna_config_ci.yaml
          test-mode: assertion
