name: Foundry

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
    
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Install foundry
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Run foundry build
              run: forge build

            - name: Run foundry fmt check
              run: forge fmt --check    

            - name: Run foundry tests
              run: forge test -vv --gas-report --ast 

            - name: Run foundry fuzzing
              run: FOUNDRY_PROFILE=ci_fuzz forge test -vv

            # - name: Run foundry coverage
            #   run: FOUNDRY_PROFILE=coverage forge coverage --report summary